<?php
require("/usr/local/www/apache22/data/inventory/faishal/fpdf/fpdf.php");
date_default_timezone_set('Asia/Makassar');

### ADD PDF
$pdf=new FPDF();


#### TOOGLE MENU
# START - REPORT Daily Activity
if ($_POST['menu']=="daily_activity"){

	# START - INDIVIDUAL REPORT
	if ($_POST['engineer']!="All"){
		if ($_POST['menucat']=="backbone-problem-internal"){
			$pdf->AddPage('L','Legal');
		} else {
			$pdf->AddPage('P','Legal');
		}
		$pdf->SetDisplayMode(real,'default');
		$pdf->SetDrawColor(188,188,188);
		$pdf->SetFont("Arial","B",20);
		if ($_POST['menucat']=="backbone-problem-internal"){
			$pdf->Cell(0,8,"PT. S-Net Indonesia",0,0,C);
			$pdf->Image('snet.gif',10,10,0,0);
		} else {
			$pdf->Cell(0,8,"PT. S-Net Indonesia",0,0,C);
			$pdf->Image('snet.gif',10,10,-150,0);
		}
		$pdf->MultiCell(0,6,"",0,0);

		$pdf->SetFont("Arial","B",12);
		$pdf->SetTextColor(255,0,0);
		if ($_POST['menucat']=="backbone-problem-internal"){
			$pdf->Cell(0,8,"DAILY ACTIVITY REPORT",0,0,C);
		} else {
			$pdf->Cell(0,8,"SERVICE OUTAGE REPORT",0,0,C);
		}
		$pdf->MultiCell(0,6,"",0,0);

		$pdf->Ln();
		$pdf->Ln();
		$pdf->Ln();

		$pdf->SetFont("Arial","B",11);
		$pdf->SetTextColor(0,0,0);

		$pdf->Cell(1,1,"Generated By",0,0);
		$pdf->Cell(50);
		$pdf->Cell(20,1,": {$_POST['name_engineer2']}",0,0);
		$pdf->MultiCell(0,5,"",0,0);

		$pdf->Cell(1,1,"Generated Date",0,0);
		$pdf->Cell(50);
		$pdf->Cell(20,1,": ".date('l, F d, o, H:i'),0,0);
		$pdf->MultiCell(0,5,"",0,0);

/*		if ($_POST['menucat']=="backbone-problem-internal"){
			$pdf->Cell(1,1,"Partner Name",0,0);
			$pdf->Cell(50);
			$pdf->Cell(20,1,": {$_POST['nama_backbone'][0]}",0,0);
			$pdf->MultiCell(0,5,"",0,0);

			$pdf->Cell(1,1,"Circuit ID",0,0);
			$pdf->Cell(50);
			$pdf->Cell(20,1,": {$_POST['circuit']}",0,0);
			$pdf->MultiCell(0,5,"",0,0);
		} else {
			$pdf->Cell(1,1,"Customer Name",0,0);
			$pdf->Cell(50);
			$pdf->Cell(20,1,": {$_POST['nama_cust']}",0,0);
			$pdf->MultiCell(0,5,"",0,0);
		}
*/
		$pdf->Cell(1,1,"Period Report",0,0);
		$pdf->Cell(50);
		$pdf->Cell(20,1,": {$_POST['rstart']} - {$_POST['rfinish']}",0,0);
		$pdf->MultiCell(0,5,"",0,0);

		$pdf->Ln();

		$pdf->SetFont("Arial","B",10);
		$pdf->Cell(5,6,"#",1,0,C);
		if ($_POST['menucat']=="backbone-problem-internal"){
			$pdf->Cell(60,6,"ENGINEER NAME",1,0,C);
		} else {
			$pdf->Cell(20,6,"ENGINEER NAME",1,0,C);
		}
		$pdf->Cell(40,6,"SUPPORT PARTS",1,0,C);
		$pdf->Cell(90,6,"ACTIVITY",1,0,C);
		$pdf->Cell(35,6,"START TIME",1,0,C);
		$pdf->Cell(35,6,"END TIME",1,0,C);
		$pdf->Cell(25,6,"DURATION",1,0,C);
		if ($_POST['menucat']=="backbone-problem-internal"){
			$pdf->Cell(0,6,"REMARK",1,1,C);
		} else {
			$pdf->Cell(0,6,"REMARK",1,1,C);
		}


		$pdf->SetFont("Arial","",10);
		$no=0;
		for ($i=0;$i<$_POST['row'];$i++){
			$pdf->Cell(5,6,$no=$no+1,1);
			if ($_POST['menucat']=="backbone-problem-internal"){
				$pdf->Cell(60,6,print_r($_POST['name_engineer'][$i],true),1);
			} else {
				$pdf->Cell(20,6,print_r($_POST['name_engineer'][$i],true),1);
			}
			$pdf->Cell(40,6,print_r($_POST['name_support_parts'][$i],true),1);
			$pdf->Cell(90,6,print_r($_POST['activity'][$i],true),1);
			$pdf->Cell(35,6,print_r($_POST['start_time'][$i],true),1);
			$pdf->Cell(35,6,print_r($_POST['end_time'][$i],true),1);
			$pdf->Cell(25,6,print_r($_POST['duration'][$i],true),1,0,C);
			if ($_POST['menucat']=="backbone-problem-internal"){
        			$pdf->Cell(0,6,print_r($_POST['remark'][$i],true),1,1);
			} else {
				$pdf->Cell(0,6,print_r($_POST['remark'][$i],true),1,1);
			}
		}

		$pdf->Ln();

		/*$pdf->SetFont("Arial","BI",10);
		$pdf->Cell(70,6,"Total Duration (DOWN) :",0,0,L);
		$pdf->Cell(0,6,"{$_POST['totdown']}",0,1,L);
		$pdf->Cell(70,6,"Total Duration (INTERMITTENT) :",0,0,L);
		$pdf->Cell(0,6,"{$_POST['totintermittent']}",0,1,L);
		$pdf->Cell(70,6,"Total TTR (DOWN):",0,0,L);
		$pdf->Cell(0,6,"{$_POST['ttrdown']}",0,1,L);
		$pdf->Cell(70,6,"Total TTR (INTERMITTENT) :",0,0,L);
		$pdf->Cell(70,6,"{$_POST['ttrintermittent']}",0,1,L);
		$pdf->Ln();
		$pdf->Cell(70,6,"SLA Result :",0,0,L);
		$pdf->Cell(0,6,"{$_POST['sladown']}",0,1,L);
		*/
		$pdf->Ln();
		$pdf->Ln();
		$pdf->Ln();

		# OUTPUT
		$pdf->output('',"RPT_SNET-DA_Individual-".date('dmy'));

	# FINISH - INDIVIDUAL BACKBONE REPORT 
	}
	# START - SUMMARY BACKBONE REPORT
	else {

		$pdf->AddPage('L','A3');
		$pdf->SetDisplayMode(real,'default');
		$pdf->SetDrawColor(188,188,188);
		$pdf->SetFont("Arial","B",20);
		$pdf->Cell(0,8,"PT. S-Net Indonesia",0,0,C);
		$pdf->Image('snet.gif',10,10,-150,0);
		$pdf->MultiCell(0,6,"",0,0);

		$pdf->SetFont("Arial","B",12);
		$pdf->SetTextColor(255,0,0);
		$pdf->Cell(0,8,"SUMMARY DAILY ACTIVITY REPORT",0,0,C);
		$pdf->MultiCell(0,6,"",0,0);

		$pdf->Ln();
		$pdf->Ln();
		$pdf->Ln();

		$pdf->SetFont("Arial","B",11);
		$pdf->SetTextColor(0,0,0);

		$pdf->Cell(1,1,"Generated By",0,0);
		$pdf->Cell(50);
		$pdf->Cell(20,1,": {$_POST['name_engineer']}",0,0);
		$pdf->MultiCell(0,5,"",0,0);

		$pdf->Cell(1,1,"Generated Date",0,0);
		$pdf->Cell(50);
		$pdf->Cell(20,1,": ".date('l, F d, o, H:i'),0,0);
		$pdf->MultiCell(0,5,"",0,0);

		$pdf->Cell(1,1,"Period Report",0,0);
		$pdf->Cell(50);
		$pdf->Cell(20,1,": {$_POST['rstart']} - {$_POST['rfinish']}",0,0);
		$pdf->MultiCell(0,5,"",0,0);

		$pdf->Ln();

		$pdf->Ln();

		$pdf->SetFont("Arial","B",10);
		$pdf->Cell(5,6,"#",1,0,C);
		$pdf->Cell(15,6,"ENGINEER NAME",1,0,C);
		$pdf->Cell(15,6,"SUPPORT PARTS",1,0,C);
		$pdf->Cell(73,6,"ACTIVITY",1,0,C);
		$pdf->Cell(20,6,"CUSTOMER NAME",1,0,C);
		$pdf->Cell(35,6,"START",1,0,C);
		$pdf->Cell(35,6,"END",1,0,C);
		$pdf->Cell(25,6,"DURATION",1,0,C);
		$pdf->Cell(100,6,"REMARK",1,0,C);


		$pdf->SetFont("Arial","",10);
		$no=0;
		for ($i=0;$i<$_POST['row'];$i++){
			$pdf->Cell(5,6,$no=$no+1,1);
			$pdf->Cell(15,6,print_r($_POST['name_engineer'][$i],true),1);
			$pdf->Cell(15,6,print_r($_POST['name_support_parts'][$i],true),1);
			$pdf->Cell(73,6,print_r($_POST['activity'][$i],true),1);
			$pdf->Cell(20,6,print_r($_POST['name_customer'][$i],true),1);
			$pdf->Cell(35,6,print_r($_POST['datetime_start'][$i],true),1);
			$pdf->Cell(35,6,print_r($_POST['datetime_end'][$i],true),1);
			$pdf->Cell(25,6,print_r($_POST['duration'][$i],true),1,0,C);
			$pdf->Cell(100,6,print_r($_POST['remark'][$i],true),1,0);
		}

		$pdf->Ln();

		# OUTPUT
                $pdf->output('',"RPT_DA_Summary-".date('dmy'));


	# FINISH - SUMMARY BACKBONE REPORT
	} 

# FINISH - REPORT BACKBONE PROBLEM
}

# START - SLA CUSTOMER - CUSTOMER CARE 
else if ($_POST['menu']=="sla-customer"){
	$pdf->AddPage('P','Legal');
	$pdf->SetDisplayMode(real,'default');
	$pdf->SetDrawColor(188,188,188);
	$pdf->SetFont("Arial","B",20);
	$pdf->Cell(0,8,"PT. SatNetCom Balikpapan",0,0,C);
	$pdf->Image('snet.gif',10,10,-150,0);
	$pdf->MultiCell(0,6,"",0,0);

	$pdf->SetFont("Arial","B",10);
	$pdf->SetTextColor(255,0,0);
	$pdf->Cell(0,8,"Customer Care Report",0,0,C);
	$pdf->MultiCell(0,6,"",0,0);
	
	$pdf->Ln();
	$pdf->Ln();
	$pdf->Ln();

	$pdf->SetFont("Arial","B",9);
	$pdf->SetTextColor(0,0,0);
	
	$pdf->Cell(1,1,"Generated By",0,0);
	$pdf->Cell(50);
	$pdf->Cell(20,1,": {$_POST['nama_engineer']}",0,0);
	$pdf->MultiCell(0,5,"",0,0);
	
	$pdf->Cell(1,1,"Generated Date",0,0);
	$pdf->Cell(50);
	$pdf->Cell(20,1,": ".date('l, F d, o, H:i'),0,0);
	$pdf->MultiCell(0,5,"",0,0);
	
	$pdf->Cell(1,1,"Customer Name",0,0);
	$pdf->Cell(50);
	$pdf->Cell(20,1,": {$_POST['nama_cust']}",0,0);
	$pdf->MultiCell(0,5,"",0,0);
	
	$pdf->Cell(1,1,"Period Report",0,0);
	$pdf->Cell(50);
	$pdf->Cell(20,1,": {$_POST['rstart']} - {$_POST['rfinish']}",0,0);
	$pdf->MultiCell(0,5,"",0,0);
	
	$pdf->Ln();
	
	$pdf->SetFont("Arial","B",8);
	$pdf->Cell(5,6,"#",1,0,C);
	$pdf->Cell(15,6,"SWOS",1,0,C);
	$pdf->Cell(15,6,"STATUS",1,0,C);
	$pdf->Cell(20,6,"SOURCE",1,0,C);
	$pdf->Cell(30,6,"START",1,0,C);
	$pdf->Cell(30,6,"FINISH",1,0,C);
	$pdf->Cell(25,6,"DURATION",1,0,C);
	$pdf->Cell(20,6,"CATEGORY",1,0,C);
	$pdf->Cell(0,6,"PROBLEM DESCRIPTION",1,1,C);
	
	
	$pdf->SetFont("Arial","",8);
	$no=0;
	for ($i=0;$i<$_POST['row'];$i++){
		$pdf->Cell(5,6,$no=$no+1,1,0);
		$pdf->Cell(15,6,print_r($_POST['swos'][$i],true),1,0);
		$pdf->Cell(15,6,print_r($_POST['status_jobtodo'][$i],true),1,0);
		$pdf->Cell(20,6,print_r($_POST['nama_terima_pekerjaan'][$i],true),1,0);
		$pdf->Cell(30,6,print_r($_POST['datetime_open'][$i],true),1,0);
		$pdf->Cell(30,6,print_r($_POST['datetime_finish'][$i],true),1,0);
		$pdf->Cell(25,6,print_r($_POST['duration'][$i],true),1,0);
		$pdf->Cell(20,6,print_r($_POST['nama_detail_pekerjaan'][$i],true),1,0);
		$pdf->MultiCell(0,6,print_r($_POST['nama_job_to_do'][$i],true),1,1);
	}


	$pdf->Ln();

	# OUTPUT
	$pdf->output('',"RPT_CCare-{$_POST['nama_cust'][0]}-".date('dmy'));
	
	# START - SLA CUSTOMER - CUSTOMER CARE 
}
	else if ($_POST['menu']=="item"){
	$pdf->AddPage('L','Legal');
	$pdf->SetDisplayMode(real,'default');
	$pdf->SetDrawColor(188,188,188);
	$pdf->SetFont("Arial","B",20);
	$pdf->Cell(0,8,"PT. S Net Indonesia",0,0,C);
	$pdf->Image('snet.gif',10,10,-150,0);
	$pdf->MultiCell(0,6,"",0,0);

	$pdf->SetFont("Arial","B",10);
	$pdf->SetTextColor(255,0,0);
	$pdf->Cell(0,8,"ITEM REPORT",0,0,C);
	$pdf->MultiCell(0,6,"",0,0);
	
	$pdf->Ln();
	$pdf->Ln();
	$pdf->Ln();

	$pdf->SetFont("Arial","B",9);
	$pdf->SetTextColor(0,0,0);
	
	$pdf->Cell(1,1,"Generated By",0,0);
	$pdf->Cell(50);
	$pdf->Cell(20,1,": {$_POST['name_engineer']}",0,0);
	$pdf->MultiCell(0,5,"",0,0);
	
	$pdf->Cell(1,1,"Generated Date",0,0);
	$pdf->Cell(50);
	$pdf->Cell(20,1,": ".date('l, F d, o, H:i'),0,0);
	$pdf->MultiCell(0,5,"",0,0);

	
	$pdf->Ln();
	
	
	$pdf->SetFont("Arial","B",10);
		$pdf->Cell(8,6,"#",1,0,C);
		if ($_POST['menucat']=="backbone-problem-internal"){
			$pdf->Cell(38,6,"SERIAL NUMBER",1,0,C);
		} else {
			$pdf->Cell(38,6,"SERIAL NUMBER",1,0,C);
		}
		$pdf->Cell(42,6,"TYPE NAME",1,0,C);
		$pdf->Cell(45,6,"MODEL NAME",1,0,C);
		$pdf->Cell(37,6,"PURCHASED FROM",1,0,C);
		$pdf->Cell(35,6,"PURCHASE DATE",1,0,C);
		$pdf->Cell(25,6,"CONTRACT",1,0,C);
		$pdf->Cell(50,6,"LOCATION",1,0,C);
		$pdf->Cell(18,6,"STATUS",1,0,C);
		if ($_POST['menucat']=="backbone-problem-internal"){
			$pdf->Cell(0,6,"REMARK",1,1,C);
		} else {
			$pdf->Cell(0,6,"REMARK",1,1,C);
		}


		$pdf->SetFont("Arial","",10);
		$no=0;
		for ($i=0;$i<$_POST['row'];$i++){
			$pdf->Cell(8,6,$no=$no+1,1);
			if ($_POST['menucat']=="backbone-problem-internal"){
				$pdf->Cell(38,6,print_r($_POST['serial_number'][$i],true),1);
			} else {
				$pdf->Cell(38,6,print_r($_POST['serial_number'][$i],true),1);
			}
			$pdf->Cell(42,6,print_r($_POST['name_type'][$i],true),1);
			$pdf->Cell(45,6,print_r($_POST['name_model'][$i],true),1);
			$pdf->Cell(37,6,print_r($_POST['from_purchase'][$i],true),1,0,C);
			$pdf->Cell(35,6,print_r($_POST['date_purchase'][$i],true),1,0,C);
			$pdf->Cell(25,6,print_r($_POST['contract_condition'][$i],true),1,0,C);
			$pdf->Cell(50,6,print_r($_POST['name_customer'][$i],true),1);
			$pdf->Cell(18,6,print_r($_POST['status'][$i],true),1,0,C);
			if ($_POST['menucat']=="backbone-problem-internal"){
        			$pdf->Cell(0,6,print_r($_POST['remark'][$i],true),1,1);
			} else {
				$pdf->Cell(0,6,print_r($_POST['remark'][$i],true),1,1);
			}
		}
	

	$pdf->Ln();

	# OUTPUT
	$pdf->output('',"Item-Report-".date('dmy'));


# END - HISTORY BACKBONE PROBLEM
}
# INVALID MENU
else {
	print "INVALID MENU";
}
?>
